### ISSUE TITLE
[Bug]: node-red crashes after this package is installed

### ISSUE THREAD

**Issue by gshpychka** [mauricedominic/node-red-contrib-huemagic#13]
### Node-Red-Contrib-Huemagic-Fork Version

4.2.8

### Node JS Version

18.14.2

### NPM Version

8.19.3

### Node-Red Version

3.0.2

### Operating System

NixOS

### What happened?

After installing this package with `npm install`, node-red crashes on startup.

### How to reproduce?

For me, it is simply:
1. `npm install node-red-contrib-huemagic-fork` in the user directory
2. restart node-red

### Expected behavior:

Node-red works well

### Additional comments?

Additional comments here, if any.

### Relevant log output

```shell
Apr 13 17:27:34 haven node-red[4598]: 13 Apr 17:27:34 - [info] Starting flows
Apr 13 17:27:34 haven node-red[4598]: 13 Apr 17:27:34 - [info] Started flows
Apr 13 17:27:34 haven node-red[4598]: 13 Apr 17:27:34 - [info] [zigbee2mqtt-server:mosquitto] MQTT Connected
Apr 13 17:27:34 haven node-red[4598]: 13 Apr 17:27:34 - [info] [zigbee2mqtt-server:mosquitto] MQTT Subscribed to: "zigbee2mqtt/#
Apr 13 17:27:40 haven node-red[4598]: 13 Apr 17:27:40 - [red] Uncaught Exception:
Apr 13 17:27:40 haven node-red[4598]: 13 Apr 17:27:40 - [error] Api Error: Unexpected response status; 404
Apr 13 17:27:40 haven node-red[4598]:     at requireStatusCode200 (/var/lib/node-red/node_modules/node-hue-api/hue-api/httpPromise.js:100:15)
Apr 13 17:27:40 haven node-red[4598]:     at _fulfilled (/var/lib/node-red/node_modules/q/q.js:787:54)
Apr 13 17:27:40 haven node-red[4598]:     at /var/lib/node-red/node_modules/q/q.js:816:30
Apr 13 17:27:40 haven node-red[4598]:     at Promise.promise.promiseDispatch (/var/lib/node-red/node_modules/q/q.js:749:13)
Apr 13 17:27:40 haven node-red[4598]:     at /var/lib/node-red/node_modules/q/q.js:557:44
Apr 13 17:27:40 haven node-red[4598]:     at flush (/var/lib/node-red/node_modules/q/q.js:108:17)
Apr 13 17:27:40 haven node-red[4598]:     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Apr 13 17:27:40 haven systemd[1]: node-red.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by gshpychka** [comment]
Something funky was going on here, not completely sure what. It seems that the issue was with another module mentioned in the log, which is not related to this package. I removed it and the crashes are gone.
